WIP: Adding configuration file support.
xyrosource/blacklung pull request #24
Opened 2017-03-14 21:30 UTC by nthorne

TODO:
  * Code cleanup.
  * Documentation.

2017-03-15 14:03 UTC, nthorne commented on src/cfg/mod.rs
> +const CONFIGFILE: &'static str = "blacklung.cfg";
Should perhaps be an argument, that defaults to this value.

2017-03-15 14:03 UTC, nthorne commented on src/cfg/mod.rs
> +    --port=<PORT>   Port to bind to. Needs to be detailed here or in configuration file.
... as an argument or a configuration item.

2017-03-15 14:04 UTC, nthorne commented on src/main.rs
> +fn handle_error<T, V, E>(f: T) -> V
Rename to something more descriptive, and add documentation.

2017-03-15 19:33 UTC, tripokey commented on src/cfg/mod.rs
> +const CONFIGFILE: &'static str = "blacklung.cfg";
Yes, we should have an internal default value which can be overridden with a cfg file value which in turn can be overridden with a command line argument.

2017-03-15 19:56 UTC, tripokey requested changes

2017-03-15 19:56 UTC, tripokey commented on src/cfg/mod.rs
> +}
type PortType = Option<u16>;

and then use PortType in the Args and ConfigurationFile structs.

2017-03-15 19:56 UTC, tripokey commented on src/cfg/mod.rs
> +            let cfg: ConfigurationFile = from_str(data.as_str()).
data.as_str() can be replaced with &data if desired

2017-03-15 19:56 UTC, tripokey commented on src/cfg/mod.rs
> +        None    => bail!("Port not configured or given as command line argument."),
Use hardcoded default value instead

2017-03-15 19:56 UTC, tripokey commented on src/main.rs
> +fn handle_error<T, V, E>(f: T) -> V
Not anything we can use now but just for reference... https://internals.rust-lang.org/t/rfc-mentoring-opportunity-permit-in-main/4600

2017-03-15 21:16 UTC, nthorne commented on src/cfg/mod.rs
> +const CONFIGFILE: &'static str = "blacklung.cfg";
Done (for port)

2017-03-15 21:16 UTC, nthorne commented on src/cfg/mod.rs
> +    --port=<PORT>   Port to bind to. Needs to be detailed here or in configuration file.
Done

2017-03-15 21:16 UTC, nthorne commented on src/cfg/mod.rs
> +}
Good idea. Done.

2017-03-15 21:16 UTC, nthorne commented on src/cfg/mod.rs
> +            let cfg: ConfigurationFile = from_str(data.as_str()).
Done.

2017-03-15 21:17 UTC, nthorne commented on src/cfg/mod.rs
> +        None    => bail!("Port not configured or given as command line argument."),
Makes sense. Done.

2017-03-16 20:33 UTC, tripokey approved these changes

2017-03-16 20:36 UTC, merged